### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by RouterXdd**
Matrixium, cinnabarite, cinnabarrium, flame resprited fully
Byte now has turret shading
Rename file names for some blocks, units to better ordering
Nerfed range of furnance and ice flood (They really outranges turrets)

### CODE REVIEW

**Comment by rylid-umil** [comment]
i don't exactly care about the ordering, besides, it's not a priority. Also renaming file names may mess up stuff though

**Comment by rylid-umil** [comment]
but omg the new sprites are so good, also i like how you added some new things. You should probably talk to my spriter, maybe he can learn some stuff from you. Also, sorry about the sprites, iw as awful at sprites back then. (THE TERRUX UNIT SPRITES :skull:)

**Comment by rylid-umil** [comment]
what is is/weapons/laserbolt.png? u added that but idk what it is

**Comment by RouterXdd** [comment]
laserbolt is the ice units gun

**Pull request merged**
